/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_kaoriya_qb_unexpected_alignment_Native */

#ifndef _Included_net_kaoriya_qb_unexpected_alignment_Native
#define _Included_net_kaoriya_qb_unexpected_alignment_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_kaoriya_qb_unexpected_alignment_Native
 * Method:    alignment1
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_net_kaoriya_qb_unexpected_1alignment_Native_alignment1
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
